// <auto-generated />
namespace HolidayExchanges.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemovingTimePartOfExchangeDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovingTimePartOfExchangeDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202103161259227_RemovingTimePartOfExchangeDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
